# Generated by Django 4.1.2 on 2022-10-16 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("music", "0005_recordlabel_alter_song_artist_album_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="songs",
        ),
        migrations.CreateModel(
            name="SongPlayLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_played", models.DateTimeField(auto_now_add=True)),
                ("song", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="play_logs", to="music.song")),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recently_played_logs", to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
